# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanuseraddress',
            name='verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Verified'),
        ),
    ]
