# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_auto_20170729_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanuseraddress',
            name='mobile_primary',
            field=models.CharField(blank=True, max_length=128, verbose_name='Mobile Primary'),
        ),
        migrations.AlterField(
            model_name='loanuseraddress',
            name='telephone',
            field=models.CharField(blank=True, max_length=128, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='pincode',
            field=models.CharField(max_length=10, unique=True, verbose_name='Pincode'),
        ),
    ]
