# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_auto_20170716_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='ifsc_code',
            field=models.CharField(max_length=12, verbose_name='IFSC code'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='pincode',
            field=models.CharField(max_length=6, verbose_name='Pincode'),
        ),
    ]
