# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_auto_20170716_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanuseraddress',
            name='email',
            field=models.CharField(blank=True, max_length=128, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='loanuseraddress',
            name='landmark',
            field=models.CharField(blank=True, max_length=128, verbose_name='Landmark'),
        ),
        migrations.AlterField(
            model_name='loanuseraddress',
            name='latitude',
            field=models.CharField(blank=True, max_length=128, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='loanuseraddress',
            name='longitude',
            field=models.CharField(blank=True, max_length=128, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='loanuseraddress',
            name='mobile_secondary',
            field=models.CharField(blank=True, max_length=128, verbose_name='Mobile Secondary'),
        ),
        migrations.AlterField(
            model_name='loanuseraddress',
            name='survey_no',
            field=models.CharField(blank=True, max_length=128, verbose_name='Survey Number'),
        ),
        migrations.AlterField(
            model_name='loanuseraddress',
            name='thaluk',
            field=models.CharField(blank=True, max_length=128, verbose_name='Thaluk'),
        ),
        migrations.AlterField(
            model_name='loanuseraddress',
            name='village',
            field=models.CharField(blank=True, max_length=128, verbose_name='Village'),
        ),
    ]
