# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_auto_20170716_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetail',
            name='job_no',
            field=models.CharField(blank=True, max_length=128, verbose_name='Job No'),
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='loan_account_no',
            field=models.CharField(blank=True, max_length=128, verbose_name='Loan account No'),
        ),
    ]
