# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_auto_20170716_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetail',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.Branch'),
        ),
    ]
