# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0008_auto_20170716_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanuseraddress',
            name='mark_borders',
            field=models.CharField(blank=True, max_length=256, verbose_name='Mark borders'),
        ),
    ]
